In [52]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [68]:
import sys
sys.path.insert(0, '../')
import numpy as np
from sklearn.metrics import accuracy_score, average_precision_score
import scipy

In [54]:
import pickle

In [55]:
with open('../data/results/fs-22050~n_fft-1024~hop_length-256~n_mels-128~mono-True~time_slice-1~normalize-True/base_network-resnet18~transfer-0~mono-True~epochs-100~lr-0.001/output_strategy-1.pkl', 'rb') as f:
    preds = pickle.load(f)

In [56]:
len(preds)

2108

In [57]:
preds[0][0].shape

(1, 11)

In [58]:
y_pred = np.vstack([p[0] for p in preds])
y_predr = np.round(y_pred)
y_true = np.vstack([p[1] for p in preds])

In [59]:
y_true[0, :]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [60]:
y_predr[0, :]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [61]:
# y_pred = np.round(scipy.special.expit(y_pred))

In [62]:
y_pred[0, :]

array([9.9906477e-04, 5.7574284e-06, 8.9533823e-05, 6.1464531e-09,
       9.9787760e-01, 1.3877316e-04, 1.5181373e-08, 1.7241042e-05,
       2.6722824e-07, 2.1180644e-05, 2.8935377e-05], dtype=float32)

In [67]:
accuracy_score(y_true, y_pred > 0.5)

0.17789373814041745

In [18]:
y_pred

array([[0.61894304, 0.6061991 , 0.5293183 , ..., 0.45788375, 0.36806953,
        0.6935406 ],
       [0.5993332 , 0.5701853 , 0.52685094, ..., 0.45042455, 0.36270928,
        0.66767985],
       [0.5883066 , 0.5789982 , 0.55278474, ..., 0.44680685, 0.36616692,
        0.6556128 ],
       ...,
       [0.58517313, 0.6079625 , 0.53300965, ..., 0.44046772, 0.37696412,
        0.7111246 ],
       [0.58455426, 0.57793874, 0.52494437, ..., 0.44693458, 0.36935884,
        0.6841459 ],
       [0.5734093 , 0.5641717 , 0.5194937 , ..., 0.4416361 , 0.36986357,
        0.67015356]], dtype=float32)

In [20]:
np.sum(y_pred)

0.0

In [69]:
average_precision_score(y_true, y_pred)

0.3681500026303684